### PR TITLE
Fix For Incorrect Row Index On Edit

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/datatable-translatable/11)

### CODE REVIEW

**Comment by RoyalSix** [comment]
I used the pattern described by react here: https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often

This was the only way I could get the variable `page` and `rowsPerPage` to propagate down without rewriting a lot of code. Hopefully in the future we can find a more robust approach, but for now this will fix the issue.

Note the example here:
```
function Example(props) {
  // Keep latest props in a ref.
  const latestProps = useRef(props);
  useEffect(() => {
    latestProps.current = props;
  });

  useEffect(() => {
    function tick() {
      // Read latest props at any time
      console.log(latestProps.current);
    }

    const id = setInterval(tick, 1000);
    return () => clearInterval(id);
  }, []); // This effect never re-runs
}
```

**Comment by ancientTexts-net** [comment]
@RoyalSix @elsylambert - I might be misunderstanding how to use the control here.
But it does not seem to save correctly for me?

Does seem to behave differently than PROD, but please see screencap here:

pr-11-dtt

**Comment by ancientTexts-net** [comment]
:lgtm:

**Comment by ancientTexts-net** [comment]
___
*[src/components/cell/Cell.js, line 40 at r2](https://reviewable.io/reviews/unfoldingword/datatable-translatable/11#-MC7JCWw9ObGs3Q2i1eO:-MC7JCWw9ObGs3Q2i1eP:b-9l0so0) ([raw file](https://github.com/unfoldingword/datatable-translatable/blob/cf2d6dee8139a3a66bc11167f305254a25b5d39b/src/components/cell/Cell.js#L40)):*
> ```JavaScript
>       rowsPerPage, 
>       page
>     } = latestProps.current;
> ```

I don't see how `options` gets in here from DataTable?

**Comment by ancientTexts-net** [comment]
Testable in RCL:
DatatableTranslatable `v0.8.4`
https://datatable-translatable.netlify.app/

**Pull request merged**
