### PR TITLE
Bugfix klappy filter options

### PR DESCRIPTION
**Pull request by klappy**
Addresses #44 and #68

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/datatable-translatable/5)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Screen Shot 2020-02-14 at 11 30 25 AM
There are permanent chips for the filters at the top left now that I can not close. I am not seeing these on the master build. Any idea why they are showing up? @klappy

**Comment by klappy** [comment]
___
*[src/components/datatable/DataTable.context.js, line 57 at r1](https://reviewable.io/reviews/unfoldingword/datatable-translatable/5#-M04DlYxCN8B8Nt5pJ0t:-M04PrvK4TrOm12uxlMw:b9itmgl) ([raw file](https://github.com/unfoldingword/datatable-translatable/blob/60016a66bec0dff67e2d7592fd6a4ad72d55bbec/src/components/datatable/DataTable.context.js#L57)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Do we still need to do this or is it managed by the library as well? @klappy 
</blockquote></details>

This one is for the actual options in the drop down list. We have to generate these since the raw data has duplicate entries. This is the part of the code that we call to generate the deduped  list.

**Comment by klappy** [comment]
> Screen Shot 2020-02-14 at 11 30 25 AM
> 
> There are permanent chips for the filters at the top left now that I can not close. I am not seeing these on the master build. Any idea why they are showing up? @klappy

How did you setup the app to use the pre-release RCL? Are you able to recreate that at the RCL level prior to implementing the changes into the app?

**Comment by klappy** [comment]
Delimiters are required, I went ahead and updated the component for defaultProps and added it to propTypes.

**Pull request merged**
