### PR TITLE
Fix for persisting Filters, update MD-translatable

### PR DESCRIPTION
**Pull request by klappy**
## Should address: 
- https://github.com/unfoldingWord/gateway-language-translation-suite/issues/37
- https://github.com/unfoldingWord/gateway-language-translation-suite/issues/38

## Should also address chip display portion: 
- https://github.com/unfoldingWord/gateway-language-translation-suite/issues/44

## Test by running styleguide:
(keep in mind rows are jumbled on purpose)
1. Filter to chapter 1, should display chip label properly.
2. Edit a cell.
3. Move Rows up and down.
4. Filter should persist and not reset.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/datatable-translatable/1)

### CODE REVIEW

**Comment by RoyalSix** [comment]
[datatable-translatable-1.mov.zip](https://github.com/unfoldingWord/datatable-translatable/files/4060071/datatable-translatable-1.mov.zip)

Is this happening as expected? @klappy

**Comment by klappy** [comment]
That behavior is what is expected. There are some things that feel odd due to the jumbled nature of the target file's rows.

**Comment by klappy** [comment]
___
*[src/components/datatable/DataTable.js, line 25 at r1](https://reviewable.io/reviews/unfoldingword/datatable-translatable/1#-LyZjKYuC4l0nvyu9vss:-LyZm-rbDNI9qd2R94jK:b-gj8tya) ([raw file](https://github.com/unfoldingword/datatable-translatable/blob/39f65e911c706b7ef444b8df86cadd43ba5f3bf0/src/components/datatable/DataTable.js#L25)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Just making sure this is meant to be an object because it has "List" in the name 
</blockquote></details>

Great catch!

**Comment by klappy** [comment]
___
*[src/components/datatable/DataTable.js, line 25 at r1](https://reviewable.io/reviews/unfoldingword/datatable-translatable/1#-LyZjKYuC4l0nvyu9vss:-LyZm1oQDS08uXnQtWnZ:b-896fix) ([raw file](https://github.com/unfoldingword/datatable-translatable/blob/39f65e911c706b7ef444b8df86cadd43ba5f3bf0/src/components/datatable/DataTable.js#L25)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Great catch!
</blockquote></details>

Done.

**Pull request merged**
